# Essential Python for DA

- Object Oriented Programming
- Read and Write file
- Context Manager
- Handle Error
- Pandas & Numpy (on demand)
- Request API

##OOP

- attributes: name, species, age
- methods: function bark(), hbd()

In [10]:
class Dog:
    def __init__(self, name, species, age):
        self.name = name
        self.species = species
        self.age = age
    def bark(self):
        print(f"{self.name}: Woof!")
    def hbd(self):
        self.age += 1

In [11]:
## attributes
dog1 = Dog("milo","Chihuahua",3)
dog2 = Dog("david","Husky",6)

In [9]:
print(f"{dog1.name} is {dog1.species}.")
print(f"{dog2.name} is {dog2.species}.")
dog1.bark()

milo is Chihuahua.
david is Husky.
milo: Woof!

In [15]:
print(dog1.name+" is "+str(dog1.age)+" years old.")
dog1.hbd()
print(dog1.name+" is "+str(dog1.age)+" years old.")

milo is 5 years old.
milo is 6 years old.

In [ ]:
## Homework OOP for an ATM

## deposit, withdraw, check balance, OTP, order coffee, pay bill, internet etc.

In [31]:
class ATM:
    def __init__(self, user_name, bank_name,balance):
        self.user_name = user_name
        self.bank_name = bank_name
        self.balance = balance
        print(f"{self.user_name} opens a new account at {self.bank_name}.")

    def __str__(self) -> str:
        return f"{self.user_name} use self.bank_name account and has {self.balance} THB."

    def check_balance(self):
        print(f"{self.user_name} has {self.balance} baht in their account.")

    def deposit(self,amount):
        self.balance += amount
        print(f"Deposit {amount} THB successfully!!"
              f"Your new balance is {self.balance} THB.")

In [32]:
fc = ATM("Phasin","scb",1000)

print(fc)

fc.check_balance()

fc.deposit(500)

Phasin opens a new account at scb.
Phasin use self.bank_name account and has 1000 THB.
Phasin has 1000 baht in their account.
Deposit 500 THB successfully!!Your new balance is 1500 THB.

In [35]:
## super class
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age

## extension
class Employee(Person):
    def __init__(self, name, age, company):
        super().__init__(name,age)
        self.company = company
    def greeting(self):
        print("Hello world")

In [36]:
person1 = Person("Phasin",28)
person1.greeting()

AttributeError: 'Person' object has no attribute 'greeting'

In [37]:
person2 = Employee("Lisa",35,"google")
person2.greeting()

Hello world

## Try Except Block

In [1]:
try:
    result = 1/0
except:
    print("this is an error message!!!!")

this is an error message!!!!

In [2]:
!cat hotel.csv

hotel_id,name,city,star_rating,price_per_night
101,Grand Plaza,New York,5,350
102,Ocean View,Miami,4,220
103,Mountain Retreat,Denver,4,185
104,The Urban Stay,Chicago,3,140
105,Sunset Resort,Los Angeles,5,410
106,Desert Inn,Phoenix,3,95
107,Heritage House,Boston,4,210
108,Lakeside Lodge,Seattle,3,130
109,Golden Gate Suites,San Francisco,5,380
110,Central Boutique,Austin,4,195

In [3]:
## read file
import csv

In [9]:
try:
    file = open("hotel.csv","r") ## r w a

    data = csv.reader(file)

    for row in data:
        print(row)

    file.close()
except FileNotFoundError:
    print("please chaeck file name again!!!")

finally:
    print("read file succesfully!!!")

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']
['101', 'Grand Plaza', 'New York', '5', '350']
['102', 'Ocean View', 'Miami', '4', '220']
['103', 'Mountain Retreat', 'Denver', '4', '185']
['104', 'The Urban Stay', 'Chicago', '3', '140']
['105', 'Sunset Resort', 'Los Angeles', '5', '410']
['106', 'Desert Inn', 'Phoenix', '3', '95']
['107', 'Heritage House', 'Boston', '4', '210']
['108', 'Lakeside Lodge', 'Seattle', '3', '130']
['109', 'Golden Gate Suites', 'San Francisco', '5', '380']
['110', 'Central Boutique', 'Austin', '4', '195']
read file succesfully!!!

In [11]:
# context manager เปิดปิดไฟล์อัตโนมัติ

read_data=[]

with open("hotel.csv","r") as file: ## r w a
    data = csv.reader(file)
    for row in data:
        read_data.append(row)

In [12]:
# header
read_data[0]

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']

In [13]:
# Body data
read_data[1:]

[['101', 'Grand Plaza', 'New York', '5', '350'],
 ['102', 'Ocean View', 'Miami', '4', '220'],
 ['103', 'Mountain Retreat', 'Denver', '4', '185'],
 ['104', 'The Urban Stay', 'Chicago', '3', '140'],
 ['105', 'Sunset Resort', 'Los Angeles', '5', '410'],
 ['106', 'Desert Inn', 'Phoenix', '3', '95'],
 ['107', 'Heritage House', 'Boston', '4', '210'],
 ['108', 'Lakeside Lodge', 'Seattle', '3', '130'],
 ['109', 'Golden Gate Suites', 'San Francisco', '5', '380'],
 ['110', 'Central Boutique', 'Austin', '4', '195']]

In [15]:
## for loop to calculate avg. price per night
prices = []

for row in read_data[1:]:
    prices.append(int(row[-1]))
print(f"Average price pernight: {sum(prices)/len(prices)}")

Average price pernight: 231.5

In [19]:
## modern python
import pandas as pd

df = pd.read_csv("hotel.csv")

print(df.head(5))

print(df.price_per_night.mean())

print(df["price_per_night"].mean())

   hotel_id              name         city  star_rating  price_per_night
0       101       Grand Plaza     New York            5              350
1       102        Ocean View        Miami            4              220
2       103  Mountain Retreat       Denver            4              185
3       104    The Urban Stay      Chicago            3              140
4       105     Sunset Resort  Los Angeles            5              410
231.5
231.5

## Read&Write Files

In [20]:
import csv

# write file + context manager
head = ["id", "name", "city"]
body = [
    [1, "John", "New York"],
    [2, "Jane", "London"],
    [3, "Jany", "London"],
]

with open("school.csv","w") as file:
    writer = csv.writer(file)
    writer.writerow(head)
    writer.writerows(body)

In [25]:
!ls
!cat school.csv

hotel.csv  sample_data	school2.csv  school.csv
id,name,city
1,John,New York
2,Jane,London
3,Jany,London

In [24]:
# modern python
import pandas as pd

df = pd.read_csv("school.csv")
print(df.head())

# export csv file in pandas
df.to_csv("school2.csv")

   id  name      city
0   1  John  New York
1   2  Jane    London
2   3  Jany    London

In [26]:
!cat school2.csv

,id,name,city
0,1,John,New York
1,2,Jane,London
2,3,Jany,London

In [27]:
## Read data from internet
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/penguins.csv"

df_penguin = pd.read_csv(url)

In [28]:
df_penguin.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [30]:
df_penguin.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [36]:
## select column
df_penguin[["species","island","body_mass_g"]].head(10)

  species     island  body_mass_g
0  Adelie  Torgersen       3750.0
1  Adelie  Torgersen       3800.0
2  Adelie  Torgersen       3250.0
3  Adelie  Torgersen          NaN
4  Adelie  Torgersen       3450.0
5  Adelie  Torgersen       3650.0
6  Adelie  Torgersen       3625.0
7  Adelie  Torgersen       4675.0
8  Adelie  Torgersen       3475.0
9  Adelie  Torgersen       4250.0

In [44]:
## filter row
df_penguin[["species","island","body_mass_g"]]\
.query("species == 'Adelie' and island == 'Dream'")\
.head(10)

   species island  body_mass_g
30  Adelie  Dream       3250.0
31  Adelie  Dream       3900.0
32  Adelie  Dream       3300.0
33  Adelie  Dream       3900.0
34  Adelie  Dream       3325.0
35  Adelie  Dream       4150.0
36  Adelie  Dream       3950.0
37  Adelie  Dream       3550.0
38  Adelie  Dream       3300.0
39  Adelie  Dream       4650.0

In [ ]:
## R vs. Python
# df %>%# select() %>%
# filter() %>%
# arrange()


# df.select()\
# .filter()\
# .arrange()

In [45]:
## filter without query()
df_penguin[df_penguin['body_mass_g'] >= 4500][["species", "sex", "body_mass_g"]]

    species     sex  body_mass_g
7    Adelie    MALE       4675.0
17   Adelie    MALE       4500.0
39   Adelie    MALE       4650.0
45   Adelie    MALE       4600.0
81   Adelie    MALE       4700.0
..      ...     ...          ...
338  Gentoo  FEMALE       4925.0
340  Gentoo  FEMALE       4850.0
341  Gentoo    MALE       5750.0
342  Gentoo  FEMALE       5200.0
343  Gentoo    MALE       5400.0

[118 rows x 3 columns]

# Requests

How to get data via API the easy way

In [46]:
import requests
## api endpoint
url = "https://swapi.info/api/people/1"

In [48]:
response = requests.get(url)

In [51]:
response.json()["name"]

'Luke Skywalker'

In [52]:
response.json()["height"]

'172'

In [53]:
response.json()["mass"]

'77'

In [57]:
## for loop
import requests
import time

characters=[]
for i in range(10):
    url = f"https://swapi.info/api/people/{i+1}"
    response = requests.get(url)
    response_json = response.json()
    data = [response_json["name"],
            response_json["height"],
            response_json["mass"],
            ]

    characters.append(data)
    #time.sleep(1)

print(characters)

[['Luke Skywalker', '172', '77'], ['C-3PO', '167', '75'], ['R2-D2', '96', '32'], ['Darth Vader', '202', '136'], ['Leia Organa', '150', '49'], ['Owen Lars', '178', '120'], ['Beru Whitesun lars', '165', '75'], ['R5-D4', '97', '32'], ['Biggs Darklighter', '183', '84'], ['Obi-Wan Kenobi', '182', '77']]

In [60]:
import pandas as pd

starwars = pd.DataFrame(characters, columns=["name","height","mass"])

starwars

                 name height mass
0      Luke Skywalker    172   77
1               C-3PO    167   75
2               R2-D2     96   32
3         Darth Vader    202  136
4         Leia Organa    150   49
5           Owen Lars    178  120
6  Beru Whitesun lars    165   75
7               R5-D4     97   32
8   Biggs Darklighter    183   84
9      Obi-Wan Kenobi    182   77